### ISSUE TITLE
Attributes: Default value does not work

### ISSUE THREAD

**Issue by Innders** [ynput/ayon-backend#264]
### To reproduce

1. Add a default value to an attribute
2. Create a new folder
3. Default value to attribute is not used

### Expected behavior

The default value be set for the folders attribute.

**Comment by martastain** [comment]
This is actually intentional. Only project attributes can have defaults since otherwise "default" logic would interfere with inherited attributes (should it be evaluated as inherited? would inheritance take a precedence? )

![image](https://github.com/user-attachments/assets/f43f2b6a-603f-49eb-a00b-d0543bb50ead)

**Comment by Innders** [comment]
Maybe @mkolar can answer this but I would say `defaultValue` always takes precedence over `inheritance`.

**Comment by martastain** [comment]
That would be a really breaking change. I believe we had this discussion, but we could reopen it. I think there were reasons to have it this way.
