### ISSUE TITLE
Attributes: priority

### ISSUE THREAD

**Issue by mkolar** [ynput/ayon-backend#313]
## Story

As an artist I need to know the order I should process my tasks in.
As a producer I need to prioritize tasks for for the team

### Proposal

We need to add a priority attribute to tasks and questionable maybe to folders too. If the priority behaves like other attributes, the hierarchical nature could be super useful for bumping priority of the full sequence or a all tasks within a shot.

It should also be considered, that production might want to use other attributes in a similar fashion, so I'd propose creating a more generic attribute type, that could simply be used for the built-in priority, but be reused for anything else. I think the requirements for the attribute are essentially an expanded enumerator of strings by a few parameters.

 For each enum item we would need:
- Icon
- Colour
- Label
- Name

Being able to add these parameters to string enums, we'd also open up doors to UI being able to handle many kinds of custom attribute usages like ratings and so on.

**Comment by martastain** [comment]
I like the idea of additional enum items metadata. We'll need a model for that, but it would also make enum resolvers more explicit. The key issue here will be the backwards compatibility.

**Comment by martastain** [comment]
Points to consider:

- In order to have a default value (let's say "normal") the attribute needs to be defined on a project, so new folders on the top level will inherit from it
- Attributes are site-wide, so changing the enum per project wouldn't be possible
- What are the chances someone wants to create their own priority enum anyways? As soon we have it, we will want to use  production tracking and we should be able to rely on our predefined values.
